export const Users = [
  {
    id: 1,
    profilePicture: "/assets/person/1.jpg",
    username: "John harry",
  },
  {
    id: 2,
    profilePicture: "/assets/person/2.jpg",
    username: "hen cena",
  },
  {
    id: 3,
    profilePicture: "/assets/person/3.jpg",
    username: "tonny cena",
  },
  {
    id: 4,
    profilePicture: "/assets/person/4.jpg",
    username: "John cena",
  },
  {
    id: 5,
    profilePicture: "/assets/person/5.jpg",
    username: "John cena",
  },
  {
    id: 6,
    profilePicture: "/assets/person/6.jpg",
    username: "John cena",
  },
  {
    id: 7,
    profilePicture: "/assets/person/7.jpg",
    username: "John cena",
  },
  {
    id: 8,
    profilePicture: "/assets/person/8.jpg",
    username: "John cena",
  },
  {
    id: 9,
    profilePicture: "/assets/person/9.jpg",
    username: "John cena",
  },
  {
    id: 10,
    profilePicture: "/assets/person/10.jpg",
    username: "John cena",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "this is my first post",
    photo: "/assets/post/1.jpg",
    date: "5 min ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "this is my second post",
    photo: "/assets/post/2.jpg",
    date: "15 min ago",
    userId: 2,
    like: 30,
    comment: 9,
  },
  {
    id: 3,
    desc: "this is my third post",
    photo: "/assets/post/3.jpg",
    date: "25 min ago",
    userId: 3,
    like: 32,
    comment: 9,
  },
  {
    id: 4,
    desc: "this is my fourth post",
    photo: "/assets/post/4.jpg",
    date: "35 min ago",
    userId: 4,
    like: 22,
    comment: 9,
  },
  {
    id: 5,
    desc: "this is my fifth post",
    photo: "/assets/post/5.jpg",
    date: "45 min ago",
    userId: 5,
    like: 22,
    comment: 9,
  },
  {
    id: 6,
    desc: "this is my sixth post",
    photo: "/assets/post/6.jpg",
    date: "55 min ago",
    userId: 6,
    like: 32,
    comment: 9,
  },
  {
    id: 7,
    desc: "this is my seventh post",
    photo: "/assets/post/7.jpg",
    date: "65 min ago",
    userId: 7,
    like: 32,
    comment: 9,
  },
  {
    id: 8,
    desc: "this is my eighth post",
    photo: "/assets/post/8.png",
    date: "75 min ago",
    userId: 8,
    like: 32,
    comment: 9,
  },
  {
    id: 9,
    desc: "this is my ninth post",
    photo: "/assets/post/9.jpg",
    date: "85 min ago",
    userId: 9,
    like: 32,
    comment: 9,
  },
  {
    id: 10,
    desc: "this is my tenth post",
    photo: "/assets/post/10.png",
    date: "95 min ago",
    userId: 10,
    like: 32,
    comment: 9,
  },
]